In [1]:
import numpy

M = numpy.array([[0, 50, 0, 29],
                 [0, 80, 31, 2],
                 [33, 90, 0, 75],
                 [0, 9, 0, 95]])

C = numpy.array([[-1, 0, 1],
                 [-2, 0, 2],
                 [-1, 0, 1]])

def convolution(Main, Mover):
    sizeL = len(Main[0]) - len(Mover[0])
    sizeH = len(Main) - len(Mover)
    length = sizeL
    height = sizeH
    result = numpy.zeros((height + 1, length + 1), dtype = int)
    while height >= 0 :
        length = sizeL
        while length >= 0 :
            result[height][length] = numpy.sum(numpy.multiply(Main[height:len(Mover)+height, length:len(Mover[0])+length], C))
            length -= 1
        height -= 1
    print(result)
    
def maxPooling(Main, sizeH, sizeL):
    length = sizeL
    height = sizeH
    result = numpy.zeros((len(Main)-sizeH+1, len(Main)-sizeL+1), dtype = int)
    while height >= 0 :
        length = sizeL
        while length >= 0 :
            result[height][length] = numpy.amax(Main[height:sizeH+height, length:sizeL+length])
            length -= 1
        height -= 1
    print(result)
    
def avgPooling(Main, sizeH, sizeL):
    length = sizeL
    height = sizeH
    result = numpy.zeros((len(Main)-sizeH+1, len(Main)-sizeL+1), dtype = int)
    while height >= 0 :
        length = sizeL
        while length >= 0 :
            result[height][length] = numpy.mean(Main[height:sizeH+height, length:sizeL+length])
            length -= 1
        height -= 1
    print(result)

In [2]:
print("Array M:\n", M)
print("Array C:\n", C)
print("---")
print("convolution of MxC:")
convolution(M, C)
print("maxPooling of M:")
maxPooling(M, 2, 2)
print("avgPooling of M:")
avgPooling(M, 2, 2)

Array M:
 [[ 0 50  0 29]
 [ 0 80 31  2]
 [33 90  0 75]
 [ 0  9  0 95]]
Array C:
 [[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
---
convolution of MxC:
[[  29 -192]
 [ -35  -22]]
maxPooling of M:
[[80 80 31]
 [90 90 75]
 [90 90 95]]
avgPooling of M:
[[32 40 15]
 [50 50 27]
 [33 24 42]]
