In [1]:
import nltk
from nltk.corpus import webtext
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.corpus import twitter_samples

import spacy

import numpy as np
from numpy.linalg import norm

import pandas as pd

import string

In [2]:
sentence = "I was born in Germany in 2000. Thus, I grew up in Germany."
print(sentence.split())
print(sentence.split(','))

['I', 'was', 'born', 'in', 'Germany', 'in', '2000.', 'Thus,', 'I', 'grew', 'up', 'in', 'Germany.']
['I was born in Germany in 2000. Thus', ' I grew up in Germany.']


In [3]:
sw_nltk = stopwords.words('english')
print(sw_nltk)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [4]:
text = "When I first met her she was very quiet. She remained quiet during the"
en = spacy.load('en_core_web_sm')
sw_spacy = en.Defaults.stop_words
print(sw_spacy)

{'sometime', 'me', 'therefore', 'doing', 'nevertheless', 'nobody', 'alone', 'five', 'still', 'everywhere', 'without', 'you', 'those', 'he', 'until', 'itself', 'every', 'could', 'one', 'anyway', 'can', 'not', 'several', 'whether', 'their', 'who', "'d", 'none', 'again', 'back', 'up', 'ever', 'another', 'namely', 'down', 'meanwhile', 'anyone', 'please', 'three', 'make', '’s', 'here', '’ll', 'first', 'wherein', 'thereupon', 'last', 'otherwise', 'such', 'being', 'but', 'four', '‘ll', 'though', 'more', 'already', 'whoever', 'for', "'ve", 'something', '’d', 'latterly', 'amount', 'hundred', 'nothing', 'perhaps', 'further', 'since', 'hence', 'if', 'through', 'say', 'however', 'n‘t', 'front', 'eight', 'during', 'below', 'always', 'thereafter', 'onto', 'what', 'thus', 'which', 'wherever', 'she', 'two', 'hereupon', 'quite', "'re", 'about', "'ll", 'often', 'call', 'yours', '‘m', 'never', '‘d', 'that', 'go', 'twenty', 'than', 'used', 'when', 'elsewhere', 'then', 'cannot', 'are', 'few', 'everyone', '

In [5]:
words = [word for word in text.split() if word.lower() not in sw_spacy]
new_text = " ".join(words)
print("Old length: ", len(text)," - ", text)
print("New length: ", len(new_text)," - ", new_text)

Old length:  70  -  When I first met her she was very quiet. She remained quiet during the
New length:  25  -  met quiet. remained quiet


In [6]:
w=[
[1,1,2,1,1,1,1,0,0],
[1,1,0,2,1,0,1,0,4],
[0,1,1,1,0,1,0,0,0],
[2,1,2,2,0,0,1,2,2],
[3,1,0,3,0,0,1,2,3]
]
total = [sum(x) for x in w]
print(total)

[8, 10, 4, 12, 13]


In [7]:
w_t = np.asarray(w).transpose()
wines = [ np.count_nonzero(x) for x in w_t]
IDF = (-1)*np.log(np.divide(np.asarray(wines),5))
print("wines: " + str(wines))
print("IDF : " + str(IDF))
w_tf = np.divide(w_t, total)
total2 = [sum(x) for x in w_tf.transpose()]
print("TF :\n "+ str(w_tf))
print("Total : " + str(total2))

wines: [4, 5, 3, 5, 2, 2, 4, 2, 3]
IDF : [ 0.22314355 -0.          0.51082562 -0.          0.91629073  0.91629073
  0.22314355  0.91629073  0.51082562]
TF :
 [[0.125      0.1        0.         0.16666667 0.23076923]
 [0.125      0.1        0.25       0.08333333 0.07692308]
 [0.25       0.         0.25       0.16666667 0.        ]
 [0.125      0.2        0.25       0.16666667 0.23076923]
 [0.125      0.1        0.         0.         0.        ]
 [0.125      0.         0.25       0.         0.        ]
 [0.125      0.1        0.         0.08333333 0.07692308]
 [0.         0.         0.         0.16666667 0.15384615]
 [0.         0.4        0.         0.16666667 0.23076923]]
Total : [1.0, 1.0, 1.0, 0.9999999999999999, 1.0]


In [8]:
tf_idf = np.multiply(w_tf.transpose(),IDF).transpose()
print("TF-IDF : \n" + str(tf_idf))

TF-IDF : 
[[ 0.02789294  0.02231436  0.          0.03719059  0.05149467]
 [-0.         -0.         -0.         -0.         -0.        ]
 [ 0.12770641  0.          0.12770641  0.0851376   0.        ]
 [-0.         -0.         -0.         -0.         -0.        ]
 [ 0.11453634  0.09162907  0.          0.          0.        ]
 [ 0.11453634  0.          0.22907268  0.          0.        ]
 [ 0.02789294  0.02231436  0.          0.0185953   0.01716489]
 [ 0.          0.          0.          0.15271512  0.1409678 ]
 [ 0.          0.20433025  0.          0.0851376   0.11788284]]


In [9]:
cos_sim = []
tf_idf_t = tf_idf.transpose()
for x in tf_idf_t:
    for y in tf_idf_t:
        cos_sim.append( np.dot(x, y)/(norm(x)*norm(y)) )
cos_sim = np.asarray(cos_sim).reshape(5,5)
print(cos_sim)

[[1.         0.24719255 0.77248235 0.29760068 0.04759334]
 [0.24719255 1.         0.         0.41449353 0.59122576]
 [0.77248235 0.         1.         0.20846468 0.        ]
 [0.29760068 0.41449353 0.20846468 1.         0.88698707]
 [0.04759334 0.59122576 0.         0.88698707 1.        ]]


In [10]:
sentence = "I really like python, it's pretty awesome.".split()
N = 3
grams = [sentence[i:i+N] for i in range(len(sentence)-N+1)]
for gram in grams:
    print(gram)


['I', 'really', 'like']
['really', 'like', 'python,']
['like', 'python,', "it's"]
['python,', "it's", 'pretty']
["it's", 'pretty', 'awesome.']


[['RT',
  '@KirkKus',
  ':',
  'Indirect',
  'cost',
  'of',
  'the',
  'UK',
  'being',
  'in',
  'the',
  'EU',
  'is',
  'estimated',
  'to',
  'be',
  'costing',
  'Britain',
  '£',
  '170',
  'billion',
  'per',
  'year',
  '!',
  '#BetterOffOut',
  '#UKIP'],
 ['VIDEO',
  ':',
  'Sturgeon',
  'on',
  'post-election',
  'deals',
  'http://t.co/BTJwrpbmOY'],
 ['RT',
  '@LabourEoin',
  ':',
  'The',
  'economy',
  'was',
  'growing',
  '3',
  'times',
  'faster',
  'on',
  'the',
  'day',
  'David',
  'Cameron',
  'became',
  'Prime',
  'Minister',
  'than',
  'it',
  'is',
  'today',
  '..',
  '#BBCqt',
  'http://t.co…']]